import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import Footer from "@/components/footer";
import { Header } from "@/components/ui/navbar";
import "./globals.css";

const montserrat = Montserrat({
  weight: ["300", "400", "500", "600", "700"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  variable: "--font-montserrat",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="font-sans">
      <body className={`${montserrat.variable} antialiased `}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
